sudo: required
services:
  - docker
before_install:
  - docker build -t jay887/react-app-docker -f Dockerfile.dev .
script:
  - docker run jay887/react-app-docker npm run test -- --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-748362436556"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
